{{- define "n8n.labels" -}}
app.kubernetes.io/name: n8n
app.kubernetes.io/part-of: n8n
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{- define "n8n.image" -}}
{{ .Values.image.repository }}:{{ .Values.image.tag }}
{{- end -}}

{{- define "n8n.valkey.host" -}}
n8n-valkey
{{- end -}}

{{/*
Environment shared by main, webhook and worker: the ConfigMap plus the values
that are secret.
*/}}
{{- define "n8n.env" -}}
envFrom:
  - configMapRef:
      name: n8n-env
env:
  - name: N8N_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Values.secrets.name }}
        key: encryption-key
  - name: QUEUE_BULL_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ .Values.secrets.name }}
        key: redis-password
  - name: N8N_RUNNERS_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: {{ .Values.secrets.name }}
        key: runners-auth-token
  - name: DB_POSTGRESDB_PASSWORD
    valueFrom:
      secretKeyRef:
        # Generated by CloudNativePG for the application user.
        name: {{ .Values.postgres.clusterName }}-app
        key: password
{{- end -}}

{{/*
Pod-level settings shared by the three n8n workloads. `restricted` Pod
Security compliant.
*/}}
{{- define "n8n.podSecurity" -}}
automountServiceAccountToken: false
enableServiceLinks: false
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
{{- end -}}

{{- define "n8n.containerSecurity" -}}
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
{{- end -}}

{{/*
Volumes: n8n only writes under its home directory (~/.n8n, and ~/.cache for
the compiled editor assets -- mounting just ~/.n8n crashes the main process
at start-up) and to /tmp. With Postgres, the queue and the encryption key all
external, nothing on disk needs to survive a restart, so both are emptyDir
and the root filesystem stays read-only.
*/}}
{{- define "n8n.volumeMounts" -}}
volumeMounts:
  - name: home
    mountPath: /home/node
  - name: tmp
    mountPath: /tmp
  - name: db-ca
    mountPath: /etc/n8n/db-ca
    readOnly: true
{{- end -}}

{{- define "n8n.volumes" -}}
volumes:
  - name: home
    emptyDir: {}
  - name: tmp
    emptyDir: {}
  - name: db-ca
    secret:
      # CA that signs the Postgres server certificate, kept by CloudNativePG.
      secretName: {{ .Values.postgres.clusterName }}-ca
      items:
        - key: ca.crt
          path: ca.crt
{{- end -}}

{{/* Roll the pods when the non-secret configuration changes. */}}
{{- define "n8n.configChecksum" -}}
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- end -}}

{{- define "n8n.spread" -}}
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: n8n
        app.kubernetes.io/component: {{ . }}
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: n8n
        app.kubernetes.io/component: {{ . }}
{{- end -}}


{{/*
The task runner sidecar: the process that actually executes Code-node
JavaScript and Python, outside the n8n process. It connects to the broker
n8n opens on localhost and authenticates with a shared token.
*/}}
{{- define "n8n.runnerContainer" -}}
- name: runners
  image: {{ .Values.taskRunners.image.repository }}:{{ .Values.taskRunners.image.tag | default .Values.image.tag }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  env:
    - name: N8N_RUNNERS_TASK_BROKER_URI
      value: http://127.0.0.1:5679
    - name: N8N_RUNNERS_AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets.name }}
          key: runners-auth-token
    - name: N8N_RUNNERS_TASK_TIMEOUT
      value: {{ .Values.taskRunners.taskTimeoutSeconds | quote }}
    - name: GENERIC_TIMEZONE
      value: {{ .Values.timezone | quote }}
  resources:
    {{- toYaml .Values.taskRunners.resources | nindent 4 }}
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
  volumeMounts:
    - name: runner-tmp
      mountPath: /tmp
{{- end -}}
