apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.charts.cloudnativePg.repoURL }}
    chart: {{ .Values.charts.cloudnativePg.chart }}
    targetRevision: {{ .Values.charts.cloudnativePg.version | quote }}
    helm:
      releaseName: cloudnative-pg
      valuesObject:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
  destination:
    {{- include "apps.destination" "cnpg-system" | nindent 4 }}
  syncPolicy:
    {{- include "apps.syncPolicy" . | nindent 4 }}
