#!/usr/bin/env bash
# Writes gitops/apps/env/<environment>.yaml from the outputs of infra/azure.
#
# This is the single hand-off from the Azure side to the GitOps side: client
# IDs, the vault URL, the backup container, the API server CIDR. None of it
# is secret. Commit the result -- ArgoCD reads it from git.
#
# The file is regenerated whole. Settings a person chooses (certificate
# issuer, sizing, restore) live next to it in <environment>.overrides.yaml,
# which this script never touches.
#
# Usage: scripts/render-env-values.sh [environment]     (default: prod)
#        TF=terraform scripts/render-env-values.sh      (default binary: tofu)
set -euo pipefail

ENVIRONMENT="${1:-prod}"
TF="${TF:-tofu}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/gitops/apps/env/${ENVIRONMENT}.yaml"

VALUES="$("$TF" -chdir="${ROOT}/infra/azure" output -raw gitops_env_values)"

{
  echo "# GENERATED by scripts/render-env-values.sh from \`${TF} output gitops_env_values\`."
  echo "# Nothing here is secret (client IDs, names, URLs). Commit it."
  echo "# OVERWRITTEN on every run: hand-written settings go in ${ENVIRONMENT}.overrides.yaml."
  printf '%s\n' "$VALUES"
} >"$OUT"

echo "wrote ${OUT#"${ROOT}/"}"
echo "next: git add ${OUT#"${ROOT}/"} && git commit && git push"
